---
apiVersion: platform.adomi.io/v1alpha1
kind: ApplicationType
metadata:
  name: odoo
spec:
  displayName: Odoo
  adapter: odoo
  chart:
    repoURL: {{ .Values.charts.odoo.repoURL | quote }}
    path: {{ .Values.charts.odoo.path | quote }}
    targetRevision: {{ .Values.charts.odoo.targetRevision | quote }}
  database:
    required: true
  sso:
    enabled: true
    protocol: proxy
  ingress:
    longpolling: true
  provides:
    - url
    - db
---
apiVersion: platform.adomi.io/v1alpha1
kind: ApplicationType
metadata:
  name: mailpit
spec:
  displayName: Mailpit (mail trap)
  adapter: mailpit
  chart:
    repoURL: {{ .Values.charts.mailpit.repoURL | quote }}
    path: {{ .Values.charts.mailpit.path | quote }}
    targetRevision: {{ .Values.charts.mailpit.targetRevision | quote }}
  database:
    required: false
  sso:
    enabled: true
    protocol: proxy
  provides:
    - url
    - smtp
---
apiVersion: platform.adomi.io/v1alpha1
kind: ApplicationType
metadata:
  name: superset
spec:
  displayName: Apache Superset
  adapter: superset
  chart:
    repoURL: {{ .Values.charts.superset.repoURL | quote }}
    chart: {{ .Values.charts.superset.chart | quote }}
    targetRevision: {{ .Values.charts.superset.version | quote }}
  database:
    required: true
  sso:
    enabled: true
    protocol: oauth2
    redirectPaths:
      - /oauth-authorized/authentik
  provides:
    - url
  consumes:
    - odoo-superset-datasource
